<div>
    <form action="/autenticador" class="row justify-content-md-center" method="post">
        <div class="form-group col-md-4">
            <label for="Usuario">Usuário:</label>
            <input class="form-control text-uppercase" type="text" name="usuario" id="usuario" placeholder="admin">

            <label for="senha">Senha:</label>
            <input class="form-control " type="password" name="senha" id="senha" placeholder="admin">

            <input class="btn btn-primary mt-3 btn-block" type="submit" value="Entrar" id="logar">
        </div>
    </form>
</div>