<head>
    <title>GC: Login</title>

</head>
<div>
    <form action="/authenticate" class="row justify-content-md-center mt-5" method="post">
        <div class="form-group col-md-4 bg-secondary opacity-75 border rounded p-5">
            <label for="user">Usuário:</label>
            <input class="form-control text-uppercase" type="text" name="user" id="user" placeholder="admin">

            <label for="pass">Senha:</label>
            <input class="form-control " type="password" name="pass" id="pass" placeholder="admin">

            <input class="btn btn-primary mt-3 btn-block" type="submit" value="Entrar" id="logar">
        </div>
    </form>
</div>