<head>
    <title>GC: Editar Ticket</title>
    <script src="js/editTicket.js"></script>
</head>
<div>
    <div class="row justify-content-end m-0 p-0 me-5">
        <div id="divMessage" class="alert alert-dismissible fade show mt-2 m-0 p-0 fs-6 col-10 col-md-8" role="alert" hidden>
            <p id="message" class="m-0 p-0">a</p>
            <button id="closeMessage" type="button" class="btn-close m-0 p-0" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
    <form action="/edit_ticket" method="post" id="formEditTicket">
        <div id="containerForm" class="rounded m-5 p-5 bg-light border border-dark">
            <h1 class="fw-bold pb-3">Editar Ticket</h1>

            <div class="mb-3">
                <input type="text" id="id" name="id" hidden value="<?= $_GET["id"] ?>">

                <div class="mb-3 " <?php if (!array_search('2', $_SESSION['listAccess'])) {
                                        echo 'hidden';
                                    } ?>>

                    <label for="requester" id="requesterLabel" class="ps-2 fs-4 mb-0 d-block border rounded-top bg-success text-light border-bottom-0 bg-opacity-75 ">Solicitante:</label>

                    <select name="requester" id="requester" class="form-control mb-3 bg-white border-top-0 rounded-0 rounded-bottom formInput">

                        <option value="<?= $this->data['ticket']['US_ID']; ?>" selected id="selectedRequester"><?= $this->data['ticket']['US_NOME']; ?></option>
                    </select>
                </div>

                <div class="mb-3 " <?php if (!array_search('2', $_SESSION['listAccess'])) {
                                        echo 'hidden';
                                    } ?>>
                    <label for="attendants" class="ps-2 fs-4 mb-0 d-block border rounded-top bg-success text-light border-bottom-0 bg-opacity-75">Atendente:</label>
                    <select name="attendants" id="attendants" class="form-control mb-3 bg-white border-top-0 rounded-0 rounded-bottom formInput" value="<?= $this->data['ticket']['ID_ATENDENTE']; ?>">
                        <option value="">Selecione um atendente</option>
                    </select>
                </div>


                <label for="description" class="ps-2 fs-4 mb-0 d-block border rounded-top bg-success text-light border-bottom-0 bg-opacity-75">Descricao:</label>
                <textarea name="description" id="description" cols="30" rows="10" class="form-control mb-3 bg-white border-top-0 rounded-0 rounded-bottom formInput"><?= $this->data['ticket']['CH_DESCRICAO']; ?></textarea>


                <div class="mb-3 ">
                    <label for="status" class="ps-2 fs-4 mb-0 d-block border rounded-top bg-success text-light border-bottom-0 bg-opacity-75">Estado:</label>
                    <select name="status" id="status" class="form-control mb-3 bg-white border-top-0 rounded-0 rounded-bottom">
                        <?php if ($this->data['ticket']['ID_ESTADO'] == 2) { ?>
                            <option value="2" selected>Encerrado</option>
                            <option value="4">Reabrir</option>

                        <?php } else { ?>
                            <?php foreach ($this->data['allStatus'] as $status) : ?>
                                <option value="<?= $status['ES_ID'] ?>" <?php if ($this->data['ticket']['ID_ESTADO'] == $status['ES_ID']) {
                                                                            echo "selected";
                                                                        } ?>>
                                    <?= $status['ES_DESCRICAO'] ?>
                                </option>
                            <?php endforeach ?>
                        <?php } ?>
                    </select>
                </div>

                <div id="res" hidden>
                    <label for="resolution" class="ps-2 fs-4 mb-0 d-block border rounded-top bg-success text-light border-bottom-0 bg-opacity-75">Resolução/Resposta:</label>
                    <textarea name="resolution" id="resolution" cols="30" rows="10" class="form-control mb-3 bg-white border-top-0 rounded-0 rounded-bottom formInput"><?= $this->data['ticket']['CH_RESOLUCAO']; ?></textarea>

                </div>

                <div class="text-end">
                    <input type="submit" value="Salvar" class="btn bg-primary text-light fw-bold ">
                </div>
            </div>
        </div>
    </form>
</div>