<head>
    <title>GC: Consultar Tickets</title>

</head>
<div class="mt-3 mb-3">
    <?php
    foreach ($this->data['tickets'] as $ticket) { ?>
        <div class=" p-0 m-0 container" id="<?= $ticket['CH_ID'] ?>">
            <form action="/edit_ticket">

                <input type="text" name="id" value="<?= $ticket['CH_ID'] ?>" hidden>

                <div class="btn-group p-0 m-0 h-2 pt-2 w-100 row">
                    <input type="submit" class="btn btn-secondary p-1 m-0 col-1 text-break" value="ID: <?= $ticket['CH_ID'] ?>" readonly>
                    <input type="submit" class="btn btn-success opacity-25 p-1 m-0 col-8 text-break text-nowrap overflow-hidden" value="<?= $ticket['CH_DESCRICAO'] ?>" readonly>
                    <input type="submit" class="btn btn-primary opacity-25 p-1 m-0 col-1 text-break" value="<?= $ticket['ES_DESCRICAO'] ?>" readonly>
                </div>

            </form>
        </div>
    <?php
    } ?>
</div>