<head>
    <title>GC: Novo Ticket</title>
    <script src="js/newTicket.js"></script>
</head>
<div>
    <div class="row justify-content-end m-0 p-0 me-5">
        <div id="divMessage" class="alert alert-dismissible fade show mt-2 m-0 p-0 fs-6 col-10 col-md-8 " role="alert" hidden>
            <p id="message" class="m-0 p-0">a</p>
            <button id="closeMessage" type="button" class="btn-close m-0 p-0" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

    </div>
    <form action="/create" method="post" id="formNewTicket">
        <div class="rounded m-5 p-5 bg-light border border-dark">
            <h1 class="fw-bold pb-3">Novo Ticket</h1>
            <div class="mb-3">
                <div class="mb-3 " <?php if (!array_search('5', $_SESSION['listAccess'])) {
                                        echo "hidden";
                                    }
                                    ?>>
                    <label for="requester" class="ps-2 fs-4 mb-0 d-block border rounded-top bg-success text-light border-bottom-0 bg-opacity-75">Solicitante:</label>
                    <select name="requester" id="requester" class="form-control mb-3 bg-white border-top-0 rounded-0 rounded-bottom">
                        <?php if (!array_search('5', $_SESSION['listAccess'])) {

                            echo "<option value='" . $_SESSION['id'] . "'> Current User </option>";
                        }
                        ?>>
                    </select>
                </div>

                <div>
                    <label for="description" class="ps-2 fs-4 mb-0 d-block border rounded-top bg-success text-light border-bottom-0 bg-opacity-75">Descricao:</label>
                    <textarea name="description" id="description" cols="30" rows="10" class="form-control mb-3 bg-white border-top-0 rounded-0 rounded-bottom"></textarea>
                </div>

                <div class="text-end">
                    <input type="submit" value="Enviar" class="btn bg-primary text-light fw-bold ">
                </div>
            </div>
        </div>
    </form>
</div>

<div class="modal fade" id="new" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Chamado criado com sucesso!</h1>
            </div>
            <div class="modal-body">
                <p>O número do seu chamado é: <span class="fw-bold border ps-2 pe-2" id="ticketNumber"></span></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="newTicket">Novo chamado</button>
                <button type="button" class="btn btn-success" id="goToTicket">Ir para o chamado</button>
            </div>
        </div>
    </div>
</div>