<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>

</head>

<body class="container " onload="carregar()">

    <header>
        <nav class='navbar navbar-primary bg-light navbar-expand-md mt-2 rounded border'>
            <div class="container-fluid">
                <a href="/home" class="navbar-brand text-success text-opacity-50 strong fw-semibold">Gerenciador de chamados</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menu" aria-controls="#menu" aria-expanded="false" aria-label="Menu">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="menu">
                    <ul class="nav ms-auto me-2 d-block d-md-flex list-group list-group-horizontal rounded ">

                        <li class="nav-item list-group-item p-0 bg-success bg-opacity-10 ">
                            <a href="/criar_chamado" class="nav-link ">Novo chamado</a>
                        </li>

                        <li class="nav-item list-group-item p-0 bg-success bg-opacity-10">
                            <a href="/apresenta_chamados" class="nav-link">Chamados</a>
                        </li>
                        <li class="nav-item">
                            <form class="d-flex" role="search" method="get" action="/editar_chamado">
                                <input class="m-0 list-group-item form-control rounded-0 bg-primary bg-opacity-10" type="search" placeholder="Informe o nº do chamado" aria-label="Search" name="id">
                                <button class="m-0 list-group-item bg-success text-light" type="submit">
                                    <i class="fas fa-search"></i>
                                </button>
                            </form>
                        </li>
                        <li>
                            <form action="/logout">
                                <button action="/logout" class="m-0 list-group-item rounded-end bg-danger text-light" type="submit">
                                    <i class="fas fa-sign-out-alt"></i>
                                </button>
                            </form>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>

    <article>
        <?= $this->contents() ?>
    </article>

    <footer class="row" id="rodape">
        <hr>

    </footer>
</body>

</html>